# workflow name
name: Build and deploy to github

# workflow event  push branch main
on: 
  push:
    branches: 
      - master

# tasks
jobs:
  # build and deploy   task's id
  build-and-deploy:
    # run environment
    runs-on: ubuntu-latest

    steps:
      # step name
      - name: Checkout
        uses: actions/checkout@master
      - name: Create Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install Packages and Build Application
        run: |
          npm install 
          npm run build
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: testCI
          BRANCH: master
          FOLDER: dist
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
